version: "3.2"
services:

  arvan_challenge:
    build: .
    container_name: 'arvan_challenge_container'
    ports:
      - 3000:3000
    networks:
      - arvan_challenge_network
    environment:
      - RABBITMQ_URL=amqp://root:root@rabbit_container:5672
      - POSTGRES_URL=postgres://postgres@postgres_container/arvan_challenge
      - REDIS_URL=redis://default:secret@redis_container:6379
    depends_on:
      - rabbitmq
      - database
      - redis

  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:latest
    container_name: 'rabbit_container'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - arvan_challenge_network

  postgres:
    image: docker.arvancloud.ir/postgres:16-alpine
    container_name: postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=arvan_challenge
    networks:
      - arvan_challenge_network

  redis:
    image: docker.arvancloud.ir/redis:latest
    container_name:  redis_container
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    networks:
      - arvan_challenge_network
  
networks:
  arvan_challenge_network: