version: "3.2"
services:
  charge_code:
    build: .
    container_name: "charge_code_container"
    ports:
      - 5000:5000
    networks:
      - arvan_challenge_network
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - RABBITMQ_URL=amqp://root:root@rabbitmq_container:5672
      - POSTGRES_URL=postgres://postgres:secret@postgres_container/arvan_challenge
      - REDIS_URL=redis://default:secret@redis_container:6379
      - LOGGER=true
      - WALLET_SERVICE_URL=http://localhost:3000
      - TRANSACTION_SERVICE_URL=http://localhost:4000
    depends_on:
      - rabbitmq
      - postgres
      - redis

  wallet:
    build: .
    container_name: "wallet_container"
    ports:
      - 3000:3000
    networks:
      - arvan_challenge_network
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - RABBITMQ_URL=amqp://root:root@rabbitmq:5672
      - POSTGRES_URL=postgres://postgres:secret@postgres/arvan_challenge
      - REDIS_URL=redis://default:secret@redis:6379
      - LOGGER=true
    depends_on:
      - postgres

  transaction:
    build: .
    container_name: "transaction_container"
    ports:
      - 4000:4000
    networks:
      - arvan_challenge_network
    environment:
      - PORT=4000
      - HOST=0.0.0.0
      - RABBITMQ_URL=amqp://root:root@rabbitmq:5672
      - POSTGRES_URL=postgres://postgres:secret@postgres/arvan_challenge
      - REDIS_URL=redis://default:secret@redis:6379
      - LOGGER=true
    depends_on:
      - postgres

  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:3-management
    container_name: "rabbitmq_container"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - arvan_challenge_network

  postgres:
    image: docker.arvancloud.ir/postgres:16-alpine
    container_name: postgresql_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=arvan_challenge
    networks:
      - arvan_challenge_network

  redis:
    image: docker.arvancloud.ir/redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=secret
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    networks:
      - arvan_challenge_network

networks:
  arvan_challenge_network:
