CREATE TABLE wallets(
    id BIGSERIAL PRIMARY KEY,
    phoneNumber VARCHAR(20) UNIQUE NOT NULL,
    balance INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chargeCodes(
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(1000) UNIQUE NOT NULL,
    price VARCHAR(1000) NOT NULL,
    count VARCHAR(1000) NOT NULL,
);

CREATE TABLE discountCodes(
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(1000) UNIQUE NOT NULL,
    price VARCHAR(1000) NOT NULL,
    count VARCHAR(1000) NOT NULL,
);

CREATE TABLE transactions(
    id BIGSERIAL PRIMARY KEY,
    phoneNumber VARCHAR(20) NOT NULL,
    code VARCHAR(1000),
    value VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (phoneNumber) REFERENCES wallets(phoneNumber),
    FOREIGN KEY (code) REFERENCES codes(code),
);