openapi: 3.0.3
info:
  title: Arvan Challenge
  version: 1.0.0
paths:
  /chargeCode/codeUsersLog/{code}:
    get:
      tags:
        - discount
      summary: get all users that have used this code
      parameters:
        - in: path
          name: code
          schema:
            type: string
          required: true
          description: the chargeCode for showing its users
      responses:
        '200':
          description: returns an object of users
  /chargeCode/applyCode:
    post:
      tags:
        - discount
      summary: starts a process of charging a wallet
      requestBody:
        content:
          application/json:
            schema:
                 type: object
                 properties:
                  code:
                    type: string
                  phoneNumber:
                    type: string
              
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '500':
          description: Error occured
          
  /wallet/{phoneNumber}:
    get:
      tags:
        - wallet
      summary: get wallet details of an specific phoneNumber
      parameters:
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
          description: the phoneNumber for showing its wallet details
      responses:
        '200':
          description: returns an object of wallet
          
  /transactions/{phoneNumber}:
    get:
      tags:
        - wallet
      summary: get transactions of an specific phoneNumber
      parameters:
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
          description: the phoneNumber for showing its wallet details
      responses:
        '200':
          description: returns an array of transactions done by a user